#goal definition
uint32 service_id
bool cancel_service
---
#result definition
float32 coverage
---
#feedback
int32[] sequence


#define the goal
#uint32 service_id #specify which service is requested
#---
#define the result
#float32 coverage
#---
#define a feedback message
#float32 current_coverage
